---
# file: tasks/ecs-preinit.yml
- name: create a new vpc
  ali_vpc:
#    alicloud_access_key: "{{ alicloud_access_key }}"
#    alicloud_secret_key: "{{ alicloud_secret_key }}"
    alicloud_region: "{{ alicloud_region }}"
    cidr_block: "{{ vpc_cidr_block }}"
    name: "{{ vpc_name }}"
    description: "{{ vpc_description }}"
#  when: not vpcs.vpcs
#  register: vpc
#- debug: var=vpc

#- name: create vswitch
#  ali_vswitch:
#    alicloud_access_key: '{{ alicloud_access_key }}'
#    alicloud_secret_key: '{{ alicloud_secret_key }}'
#    alicloud_region: "{{ alicloud_region }}"
#    cidr_block: "{{ vswitch_cidr_blok }}"
#    name: "{{ vswitch_name }}"
#    description: "{{ vswitch_description }}"
#    vpc_id: "{{ vpc.id }}"
#  register: vsw
#- debug: var=vsw

#- name: create a security group
#  ali_security_group:
#    alicloud_access_key: '{{ alicloud_access_key }}'
#    alicloud_secret_key: '{{ alicloud_secret_key }}'
#    alicloud_region: "{{ alicloud_region }}"
#    name: "{{ sgroups.docker-sg.name }}"
#    description: "{{  sgroups.docker-sg.description }}"
#    vpc_id: "{{vpc.id}}"
#    rules: "{{  sgroups.docker-sg.inboundRules }}"
#    rules_egress: "{{  sgroups.docker-sg.outboundRules }}"
#  register: sg
